name: "02 - Workflow Events"

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '11 10 * * *'

jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Show the trigger
      run: echo "Event for dev: '${{github.event_name}}' "



