name: "02 - Workflow Events"

on: 
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '40 11 * * *'

jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Show the trigger
      run: echo "Event name is ${{ github.event_name }}"



