name: "04 - Using Actions"

on: push 

jobs:
  build:
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4
    steps:
      - name: Printing Folder 
        run: | 
          echo "Folders: "
    steps: 
      - name: Setup Node 
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
    steps: 
      - name: Install Dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app









