name: "16 - Working with Environments"

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging

run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        env:
            MY_ENV_VALUE: ${{ vars.environment }}
            my-env-value: ${{ vars.MY_ENV_VALUE && inputs.target-env || 'default value'}}

        steps:
            - name: Echo vars
              run: |
                echo "Env variable: $my-env-value"

            



