name: "17 - 2 - Custom Actions - JS"

on:
    workflow_dispatch:
        inputs:
            base-branch:
                description: "The branch used as the base for the dependency update checks"
                default: main
                required: false
            target-branch:
                description: "The branch from which the PR is created"
                default: update-dependencies
                required: false
            working-dir:
                description: "The working directory of the project to check for dependency updates"
                default: 17-custom-actions/react-app
                required: true
            debug:
                description: "Whether the output debug messages to the console"
                required: false

run-name: 17 - 2 - Custom Actions - JS - BB ${{ inputs.base-branch}} - TB- ${{ inputs.target-branch }} WD - ${{ inputs.working-dir }} - Debug - ${{ inputs.debug }}

jobs:
    dependency-update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update
              with:
                base-branch: ${{ inputs.base-branch }}
                target-branch: ${{ inputs.target-branch }}
                working-dir: ${{ inputs.working-dir }}
