name: "17 - 3 - Custom Actions - Docker"

on:
    workflow_dispatch:
        inputs:
            url:
                type: choice
                options: 
                    - 'https://www.google.com'
                    - 'https://unsplashed44555.com/'
                    - 'my goodness.com'
                default: 'https://www.google.com'
            max-trials:
                description: "Maximum trials until action fails"
                default: '10'
                required: false
            delay:
                description: "Delay in seconds between trials"
                default: '5'

jobs:
    ping-url:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Ping URL
              id: ping-url
              uses: ./.github/actions/docker-ping-url
              with: 
                url: ${{ inputs.url }}
                max-trials: ${{ inputs.max-trials }}
                delay: ${{ inputs.delay }}

            - name: Print output from ping url 
              run: |
                echo "URL reachable: ${{ steps.ping-url.outputs.url-reachable }}"


